remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Vikash Singh]
description: [“A professional portfolio showcasing my work as a Computer Science engineering student, featuring full-stack projects using Spring Boot and React, secure web applications, 
and hands-on experience with Java C++ SQL and cloud technologies—highlighting my problem-solving skills, achievements, and readiness for software development roles.”]
